# Generated by Django 5.0.6 on 2024-08-14 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Username')),
                ('email', models.EmailField(blank=True, max_length=150, null=True, verbose_name='Email')),
                ('f_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('m_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Middle Name')),
                ('l_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Last Name')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('role', models.CharField(choices=[('STAFF', 'Staff'), ('CLIENT', 'Client'), ('VENDOR', 'Vendor')], max_length=10, verbose_name='Role for User')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active User')),
                ('is_staff', models.BooleanField(default=False, verbose_name='WBT Employee')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Administrator')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('alt_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Alternate Phone')),
                ('designation', models.CharField(max_length=50, verbose_name='Client Designation')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Billing Address')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='State')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Country')),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Zip Code')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.baseuser',),
        ),
    ]
