# Generated by Django 5.0.6 on 2024-08-16 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_client_address_alter_client_city_and_more'),
        ('department', '0004_department_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Staff_Department', to='department.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='manager',
            field=models.BooleanField(default=False, verbose_name='Project Manager'),
        ),
    ]
