# Generated by Django 5.0.6 on 2024-09-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_vendoruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendoruser',
            name='contactPoint',
            field=models.BooleanField(default=False, verbose_name='Point of contact'),
        ),
    ]
