# Generated by Django 5.0.6 on 2024-09-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_manager_staff_is_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='is_firstLogin',
            field=models.BooleanField(default=True, verbose_name='Change Password on Next Login'),
        ),
    ]
