# Generated by Django 5.0.6 on 2024-08-14 07:17

import django.db.models.deletion
import fabricator.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Fabricator Name')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Billing Address')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('state', models.CharField(max_length=50, verbose_name='State')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('zip_code', models.CharField(max_length=20, verbose_name='Zip Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.department', verbose_name='Department')),
            ],
        ),
        migrations.CreateModel(
            name='StandardDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=fabricator.models.uploadStandardDesign, verbose_name='Design File')),
                ('added_on', models.DateTimeField(auto_now_add=True, verbose_name='Added On')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
                ('fabricator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabricator.fabricator', verbose_name='Fabricator')),
            ],
        ),
    ]
