# Generated by Django 5.0.6 on 2024-08-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabricator', '0002_fabricator_drive_fabricator_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricator',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Recycle Bin'),
        ),
    ]
