# Generated by Django 5.0.6 on 2024-08-21 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabricator', '0004_rename_is_active_fabricator_is_bin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fabricator',
            name='department',
        ),
    ]
