# Generated by Django 5.0.6 on 2024-08-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('task', '0003_rename_is_active_task_is_bin'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcomment',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='tag.tag', verbose_name='Tags'),
        ),
    ]
