# Generated by Django 5.0.6 on 2024-08-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('task', '0004_taskcomment_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcomment',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tag.tag', verbose_name='Tags'),
        ),
    ]
