# Generated by Django 5.0.6 on 2024-08-16 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0004_department_manager'),
        ('fabricator', '0002_fabricator_drive_fabricator_website'),
        ('team', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Project Name')),
                ('status', models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('ON-HOLD', 'On-Hold'), ('INACTIVE', 'Inactive'), ('DELAY', 'Delay'), ('COMPLETE', 'Complete')], default='ACTIVE', max_length=55, null=True, verbose_name='Project Status')),
                ('stage', models.CharField(blank=True, choices=[('RFI', 'Request for Information'), ('IFA', 'Issue for Approval'), ('BFA', 'Back from Approval'), ('BFA-M', 'Back from Approval - Markup'), ('RIFA', 'Re-issue for Approval'), ('RBFA', 'Return Back from Approval'), ('IFC', 'Issue for Construction'), ('BFC', 'Back from Construction'), ('RIFC', 'Re-issue for Construction'), ('REV', 'Revision'), ('CO#', 'Completed')], default='IFA', max_length=55, null=True, verbose_name='Project Stage')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('approval_date', models.DateField(blank=True, null=True, verbose_name='Approval Date')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.department', verbose_name='Department')),
                ('fabricator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fabricator.fabricator', verbose_name='Fabricator')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Project_Manager', to=settings.AUTH_USER_MODEL, verbose_name='Project Manager')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='team.team', verbose_name='Teams')),
            ],
        ),
    ]
