# Generated by Django 5.0.6 on 2024-08-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_project_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='connectionDesign',
            field=models.BooleanField(default=False, verbose_name='Connection Design'),
        ),
        migrations.AddField(
            model_name='project',
            name='customerDesign',
            field=models.BooleanField(default=False, verbose_name='Customer Design'),
        ),
        migrations.AddField(
            model_name='project',
            name='miscDesign',
            field=models.BooleanField(default=False, verbose_name='Misc Design'),
        ),
        migrations.AddField(
            model_name='project',
            name='tool',
            field=models.CharField(blank=True, choices=[('TEKLA', 'TEKLA'), ('SDS-2', 'SDS-2')], default=None, max_length=20, null=True, verbose_name='Tools'),
        ),
    ]
