# Generated by Django 5.0.6 on 2024-08-16 10:49

import project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_connectiondesign_project_customerdesign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='projectcomment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=project.models.uploadProjectComment, verbose_name='Comment File'),
        ),
    ]
