# Generated by Django 5.0.6 on 2024-08-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_project_description_alter_projectcomment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Recycle Bin'),
        ),
    ]
