# Generated by Django 5.0.6 on 2024-08-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_rename_is_active_project_is_bin'),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcomment',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='tag.tag', verbose_name='Tags'),
        ),
    ]
