# Generated by Django 5.0.6 on 2024-08-14 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_remove_department_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='is_sales',
        ),
    ]
