# Generated by Django 5.0.6 on 2024-08-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_department_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Recycle Bin'),
        ),
    ]
